/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package contentpanels;

import Database.Connection;
import com.formdev.flatlaf.extras.FlatSVGIcon;
import contentpanels.BrandPanel.loopingBrandPanel;
import dialogs.AddBrandDialog;
import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Image;
import java.sql.SQLException;
import java.sql.ResultSet;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JPanel;

/**
 *
 * @author shash
 */
public class BrandsPanel extends javax.swing.JPanel {

    /**
     * Creates new form BrandsPanel
     */
    public BrandsPanel() {
        initComponents();
        init();
    }
    
    private void init(){
        
        try {
            ResultSet response =  Connection.search("SELECT * FROM `brand`");
            
            while(response.next()){
            
                loopingBrandPanel brandPanel = new loopingBrandPanel();
                brandPanel.setBrandName(response.getString("brand_name"));
                innerBrandPanel.add(brandPanel);
                
            }
            
            
        } catch (SQLException e) {
            e.printStackTrace();
        }
   
    }
    
    public void refresh(){
    
        innerBrandPanel.removeAll();
        
        try {
            ResultSet response =  Connection.search("SELECT * FROM `brand`");
            
            while(response.next()){
            
                loopingBrandPanel brandPanel = new loopingBrandPanel();
                brandPanel.setBrandName(response.getString("brand_name"));
                
                String imgpath = "product_images/" +  response.getString("img_path");
                ImageIcon icon = new ImageIcon(imgpath);
                Image image = icon.getImage().getScaledInstance(175, 248, Image.SCALE_SMOOTH);
                ImageIcon resizedone = new ImageIcon(image);
                brandPanel.setjLabel1(resizedone);
                        
                innerBrandPanel.add(brandPanel);
                
            }
            
            
        } catch (SQLException e) {
            e.printStackTrace();
        }
        
        innerBrandPanel.revalidate();
        innerBrandPanel.repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        innerBrandPanel = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));

        innerBrandPanel.setBackground(new java.awt.Color(255, 255, 255));
        innerBrandPanel.setLayout(new java.awt.GridLayout(0, 5, 20, 20));

        jButton1.setBackground(new java.awt.Color(16, 92, 92));
        jButton1.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Add Brand");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 605, Short.MAX_VALUE)
                        .addComponent(jButton1))
                    .addComponent(innerBrandPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(27, 27, 27))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addGap(18, 18, 18)
                .addComponent(innerBrandPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 342, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        new AddBrandDialog(null, true, this).setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel innerBrandPanel;
    private javax.swing.JButton jButton1;
    // End of variables declaration//GEN-END:variables
}
